# Generated by Django 3.1.13 on 2023-08-05 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230805_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_model',
            name='duration',
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 23, 2, 31, 962456)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 23, 2, 31, 962424)),
        ),
    ]
