# Generated by Django 3.1.13 on 2023-08-05 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230805_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_db',
            name='optionA',
            field=models.CharField(default='Yes', max_length=3),
        ),
        migrations.AddField(
            model_name='question_db',
            name='optionB',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 23, 7, 13, 889360)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 23, 7, 13, 889335)),
        ),
    ]
