# Generated by Django 3.1.13 on 2023-08-05 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230805_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_db',
            name='optionC',
        ),
        migrations.RemoveField(
            model_name='question_db',
            name='optionD',
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 23, 8, 47, 606963)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 23, 8, 47, 606938)),
        ),
    ]
