# Generated by Django 3.1.13 on 2023-08-05 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20230805_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 23, 9, 32, 39488)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 23, 9, 32, 39461)),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='answer',
            field=models.CharField(default='Yes', max_length=3),
        ),
    ]
